# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dash0 < Formula
  desc "CLI to interact with Dash0"
  homepage "https://github.com/dash0hq/dash0-cli"
  version "1.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.18.0/dash0_1.18.0_macos_amd64.tar.gz"
      sha256 "8f60c87b3afe323f818f1caf9b96560a9f9d4d0bfc5c48486dc30ffe25378e40"

      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.18.0/dash0_1.18.0_macos_arm64.tar.gz"
      sha256 "223c0358606e22e9e23e6a21ea4bfed02264ecc86de80fc84a341f7d623ffa46"

      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.18.0/dash0_1.18.0_linux_amd64.tar.gz"
      sha256 "a4324ed5c2adfda403b960a75e48922c3bc1f09687ec7dd61eadc8c9ff15f468"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.18.0/dash0_1.18.0_linux_arm.tar.gz"
      sha256 "4f76e09859a70b55587948632a1c032c315893f3ffcbb748ae8662f6a9cdf372"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dash0hq/dash0-cli/releases/download/v1.18.0/dash0_1.18.0_linux_arm64.tar.gz"
      sha256 "70f5296cdc294bf854d8152ba517a5b91d397da6d36fb26f693f6ebcee804ba3"
      define_method(:install) do
        bin.install "dash0"
        bash_completion.install "completions/dash0.bash" => "dash0"
        zsh_completion.install "completions/dash0.zsh" => "_dash0"
        fish_completion.install "completions/dash0.fish" => "dash0.fish"
      end
    end
  end
end
